name = "outil"
version = "0.5.0"
description = "A Gleam library for writing command line tools."
licences = ["Apache-2.0"]
repository = { type = "github", user = "fabjan", repo = "outil" }

[dependencies]
gleam_stdlib = "~> 0.32"

[dev-dependencies]
gleeunit = "~> 1.0"
