name: Publish to hex.pm

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  push-hex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0
      - uses: erlef/setup-beam@v1.16.0
        with:
          version-type: strict
          version-file: ".tool-versions"
      - run: ./publish.sh
